# Generated by Django 2.0.3 on 2019-05-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='render',
        ),
        migrations.AddField(
            model_name='reservation',
            name='book_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_to',
            field=models.CharField(default='', max_length=30),
        ),
    ]
