# Generated by Django 2.0.3 on 2019-05-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190521_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='book_name',
            new_name='book_id',
        ),
    ]
