# Generated by Django 2.0.3 on 2019-05-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20190521_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='book_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='book_name',
            field=models.CharField(default='blank', max_length=30),
        ),
    ]
